{% set version = "0.5.1" %}

package:
  name: cusolvermp
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/LICENSE.txt
  sha256: c2a95a3d181879325e56333d7a592bb6ba5ab3a44bfde9574513ccc2f87f9c68

build:
  number: 0
  noarch: generic

requirements:
  run:
    - libcal-dev 0.4.4.50
    - libcusolvermp-dev 0.5.1.690

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all NVIDIA cuSOLVERMp packages, not intended for use in a conda-build context.
  description: |
    NVIDIA cuSOLVERMp is a high-performance, distributed-memory, GPU-accelerated library that provides tools for the solution of dense linear systems and eigenvalue problems.
    cuSOLVERMp is compatible with 2D block-cyclic data layout and provides ScaLAPACK-like C APIs.
    A companion library, CAL, contains utilities to manage communicators and to synchronize processes in a safe way.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
